/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkipTokenRouteImport } from './routes/skip-token'
import { Route as ManualFetchRouteImport } from './routes/manual-fetch'
import { Route as ConditionalQueryRouteImport } from './routes/conditional-query'
import { Route as IndexRouteImport } from './routes/index'

const SkipTokenRoute = SkipTokenRouteImport.update({
  id: '/skip-token',
  path: '/skip-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualFetchRoute = ManualFetchRouteImport.update({
  id: '/manual-fetch',
  path: '/manual-fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionalQueryRoute = ConditionalQueryRouteImport.update({
  id: '/conditional-query',
  path: '/conditional-query',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conditional-query': typeof ConditionalQueryRoute
  '/manual-fetch': typeof ManualFetchRoute
  '/skip-token': typeof SkipTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conditional-query': typeof ConditionalQueryRoute
  '/manual-fetch': typeof ManualFetchRoute
  '/skip-token': typeof SkipTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conditional-query': typeof ConditionalQueryRoute
  '/manual-fetch': typeof ManualFetchRoute
  '/skip-token': typeof SkipTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conditional-query' | '/manual-fetch' | '/skip-token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conditional-query' | '/manual-fetch' | '/skip-token'
  id: '__root__' | '/' | '/conditional-query' | '/manual-fetch' | '/skip-token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConditionalQueryRoute: typeof ConditionalQueryRoute
  ManualFetchRoute: typeof ManualFetchRoute
  SkipTokenRoute: typeof SkipTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skip-token': {
      id: '/skip-token'
      path: '/skip-token'
      fullPath: '/skip-token'
      preLoaderRoute: typeof SkipTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-fetch': {
      id: '/manual-fetch'
      path: '/manual-fetch'
      fullPath: '/manual-fetch'
      preLoaderRoute: typeof ManualFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditional-query': {
      id: '/conditional-query'
      path: '/conditional-query'
      fullPath: '/conditional-query'
      preLoaderRoute: typeof ConditionalQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConditionalQueryRoute: ConditionalQueryRoute,
  ManualFetchRoute: ManualFetchRoute,
  SkipTokenRoute: SkipTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
